{% set name = "pandas-plink" %}
{% set version = "1.1.2" %}
{% set sha256 = "b892d951eac5ec8f3455f5f7b0ecfced88bbcd63c154f8404c7c92c135348140" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - cffi >=1.7
    - pytest-runner
  run:
    - python
    - cffi >=1.7
    - numpy >=1.9
    - pandas >=0.17
    - toolz >=0.8
    - dask >=0.12

test:
  requires:
    - pytest >=3
  imports:
    - pandas_plink
  commands:
    - python -c "import sys; import pandas_plink; sys.exit(pandas_plink.test())"

about:
  home: http://github.com/glimix/pandas-plink
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Convert PLINK files to Pandas data frame'
  doc_url: http://pandas-plink.readthedocs.io
  dev_url: https://github.com/glimix/pandas-plink

extra:
  recipe-maintainers:
    - Horta
