{% set name = "pandas-plink" %}
{% set version = "1.1.6" %}
{% set sha256 = "f8c5ec35de98f472aea525a2295825011fad5ab63e5f85a4ea84767c37ec2a21" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win32 or (win64 and py<35)]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - cffi >=1.7
    - pytest-runner
  run:
    - python
    - cffi >=1.7
    - numpy >=1.9
    - pandas >=0.17
    - toolz >=0.8
    - dask >=0.14

test:
  requires:
    - pytest >=3
  imports:
    - pandas_plink
  commands:
    - python -c "import sys; import pandas_plink; sys.exit(pandas_plink.test())"

about:
  home: https://github.com/limix/pandas-plink
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Convert PLINK files to Pandas data frame'
  doc_url: https://pandas-plink.readthedocs.io
  dev_url: https://github.com/limix/pandas-plink

extra:
  recipe-maintainers:
    - Horta
