travis:
  secure:
    BINSTAR_TOKEN: s6ixodqj69pcDKSgo/I252dG6/Gt3TMS4p1eEXAckLxLXd/D4cDg+2r0N14lOYjQB9uSpPR/5MynimyHvMjHF+9owmNj2Uv0w7uaXBTKWqj3TWyGzY8RMWA7uYMF8FSk3deuh3Vfzue12Z73Lh3w/4D4PUl1lMOHd5bIYVTSZIqk9ma0oP1u0Q1MGHzsIdKCe1p2c7urcrcOpFZrHTVH4OZUIPqU3TYfoQEHmfZmHQqFEQJFYu/DAEB1epWY5FvWPZWnMqRBMINlW0DUxx1MbtB2iI/QXFZ0VKp6qZbTyL9hZO4dIR6Afn+LhWBxxhEPcbPoMIdo1uAATy1ZBssc8NgA/mxRUPJPTS2guN9TrF8L203xQKEiuZHgXCz5vgvIy8jjBJ8/CEmYtaO7MUOccc2k/vDCMCVOBfWMXY1LXnzHQHdK8whTl4+F85C0TfjkuE44s2xkgvqZACBZWNOEBvwfxR1b2XJ/2YSulSMprokrBZn8pXzdpmyvXpKKFptmgSaAasdk3v8dCJVQZ743bzpPGkuBw7pggcsB2lbKHDYMFpnaU+cbNaoOBgJXuBMlX+Xbk8+CUbYeaIY24K7y2nbnc3F/y7EW0WT5p0XUApgwDGLvapJsiFtVKjCMa5JNutWqjVavGtxJDa5AV4M12O0ZQarOB++7hO2bPjO5/Bk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
